---
jobs:
- name: jumpbox_z1
  templates:
  - name: jumpbox
    release: jumpbox
  - name: shield-agent
    release: shield
  - name: toolbelt-quick
    release: toolbelt
  - name: toolbelt
    release: toolbelt
  instances: 1
  resource_pool: (( param "Specify the resource pool for the jump box" ))
  persistent_disk: 10240
  networks: (( param "Specify the network definitions for the jump box" ))
