---
networks:
- name: jumpbox
  type: manual
  subnets:
  - range: 10.244.18.0/24
    gateway: 10.244.18.1
    static:
    - 10.244.18.2 - 10.244.18.60

jobs:
- name: jumpbox
  networks:
  - name: jumpbox
    static_ips: (( static_ips 0 ))
